name: build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Test with code coverage
        run: cargo test --verbose --all-targets
